@SurvayBasket.Api_HostAddress = https://localhost:7088

GET {{SurvayBasket.Api_HostAddress}}/api/Polls
Accept: application/json

###

GET {{SurvayBasket.Api_HostAddress}}/api/Polls/1
Accept: application/json
###

GET {{SurvayBasket.Api_HostAddress}}/api/Test

###
